#!/usr/bin/env python3
"""TMT Radar -> client-alert pipeline (reference implementation).

The tracker's job ends at the feed: it says, deterministically, what every disclosed venue
published. This is the downstream step a practice runs on top of it — map each new instrument
or judgment to the clients who care, and draft an alert email a partner can review and send.

    sources -> engine -> feed (data/items.json / connector API) -> [THIS] -> client drafts

Everything here is deterministic and local. No client data leaves the machine, and the drafting
is template fill (the same discipline the memos use) — a firm that wants prose in its own house
style plugs its LLM in at the one marked step, over the same matched facts.

Run:
    python3 pipeline/pipeline.py --since 2026-08-01
    # reads data/items.json by default; pass --api to pull the live connector instead.

Outputs pipeline/drafts/<client>.md (one draft per client with matches) and an index.html the
partner can open to review them all.
"""
from __future__ import annotations

import argparse
import html
import json
import re
import urllib.request
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = Path(__file__).resolve().parent / "drafts"


def load_feed(since: str, use_api: bool) -> list:
    """The two supported inlets, both documented in docs/CONNECTOR.md."""
    if use_api:
        url = f"http://127.0.0.1:8788/v1/digest?since={since}"
        with urllib.request.urlopen(url, timeout=10) as r:  # noqa: S310 (localhost only)
            data = json.loads(r.read())
        rows = [it for grp in data.get("by_regulator", {}).values() for it in grp]
        # the digest is instruments-only; pull judgments too for a full picture
        with urllib.request.urlopen(f"http://127.0.0.1:8788/v1/judgments?since={since}", timeout=10) as r:  # noqa: S310
            rows += json.loads(r.read()).get("items", [])
        return rows
    items = json.loads((ROOT / "data" / "items.json").read_text())["items"]
    return [i for i in items if i.get("lane") in ("instruments", "judgments")
            and (i.get("date") or "") >= since]


def match(item: dict, watch: dict) -> list:
    """Why (if at all) this item is on a client's radar — plain-English reasons, or [] for no
    match. Relevance REQUIRES a subject-keyword hit: a client sees an item because of what it is
    ABOUT, not merely because it came from a regulator it follows (that alone would dump every
    tariff order and cable-TV petition on it). The watched regulator/stratum then enrich the
    'why', once the subject already matches."""
    hay = " ".join(str(item.get(k) or "") for k in ("short", "line", "title", "type"))
    hits = []
    for kw in watch.get("keywords", []):
        m = re.search(kw, hay, re.I)
        if m:
            hits.append(m.group(0).lower())
    if not hits:
        return []  # subject not relevant to this client — skip, however apt the regulator
    reasons = []
    reg = item.get("regulator") or ""
    if reg in watch.get("regulators", []):
        reasons.append(f"from {reg}, a regulator you follow")
    uniq = sorted(set(hits))
    reasons.append("mentions " + ", ".join(f"'{h}'" for h in uniq[:4]))
    return reasons


def draft_markdown(client: dict, items: list, since: str) -> str:
    n = len(items)
    lines = [
        f"**Subject:** TMT regulatory update — {n} item{'s' if n != 1 else ''} for {client['name']}",
        "",
        "Dear [client contact],",
        "",
        f"Since {fmt(since)}, the following {n} development{'s' if n != 1 else ''} on the regulatory "
        f"radar may affect {client['name']} ({client['sector']}):",
        "",
    ]
    for i, (it, reasons) in enumerate(items, 1):
        cite = it.get("citation") or (("Gazette " + it["meta"]["gazette_id"]) if (it.get("meta") or {}).get("gazette_id") else "")
        doc = it.get("doc_url") or it.get("document_url") or it.get("page_url") or ""
        lines += [
            f"{i}. **{it.get('short') or it.get('short_title') or it.get('title')}**",
            f"   {it.get('regulator')} · {(it.get('type') or '').replace('_',' ')} · {fmt(it.get('date'))}",
            f"   {it.get('line') or it.get('summary') or ''}",
            f"   *Why this is on your radar:* {'; '.join(reasons)}.",
            f"   Official text: {doc}" + (f"  ·  {cite}" if cite else ""),
            "",
        ]
    lines += [
        "We flag these automatically for your review and will follow with a considered note on any "
        "that warrant action.",
        "",
        f"Prepared for {client['partner']}, Trilegal TMT.",
        "",
        "---",
        "_DRAFT — generated by the TMT Radar pipeline for partner review. Every item must be verified "
        "against the official text before advising the client. Not sent._",
        # ── House-style prose: a firm that wants a partner-voiced narrative instead of this
        #    structured list plugs its own model in HERE, over the identical matched facts above. ──
    ]
    return "\n".join(lines)


def fmt(iso) -> str:
    if not iso or len(str(iso)) < 10:
        return str(iso or "")
    y, m, d = str(iso)[:10].split("-")
    mon = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"][int(m)-1]
    return f"{int(d)} {mon} {y}"


def preview_html(results: list, since: str) -> str:
    cards = []
    for c, items in results:
        blocks = []
        for it, reasons in items:
            doc = it.get("doc_url") or it.get("page_url") or ""
            blocks.append(
                f"<li><a href='{html.escape(doc)}' target='_blank' rel='noopener'>"
                f"{html.escape(it.get('short') or it.get('title'))}</a>"
                f"<div class='m'>{html.escape(it.get('regulator') or '')} · {html.escape(fmt(it.get('date')))} · "
                f"{html.escape(it.get('line') or '')}</div>"
                f"<div class='why'>{html.escape('; '.join(reasons))}</div></li>")
        cards.append(
            f"<section><h2>{html.escape(c['name'])} <span>{html.escape(c['sector'])}</span></h2>"
            f"<p class='cnt'>{len(items)} item{'s' if len(items)!=1 else ''} since {html.escape(fmt(since))}</p>"
            f"<ul>{''.join(blocks)}</ul></section>")
    return f"""<!doctype html><meta charset=utf-8><title>Client alert drafts</title>
<style>
body{{font-family:'IBM Plex Sans',system-ui,sans-serif;max-width:860px;margin:40px auto;padding:0 20px;color:#1a2b34}}
h1{{font-family:Spectral,Georgia,serif;font-weight:500}}
.sub{{color:#5a6b74;margin-bottom:30px}}
section{{border:1px solid #e2e8ec;border-radius:10px;padding:20px 24px;margin:18px 0}}
h2{{font-family:Spectral,Georgia,serif;font-weight:500;font-size:20px;margin:0 0 2px}}
h2 span{{font-family:'IBM Plex Mono',monospace;font-size:11px;color:#8a969d;text-transform:uppercase;letter-spacing:.08em;margin-left:8px}}
.cnt{{font-family:'IBM Plex Mono',monospace;font-size:12px;color:#AA8918;margin:0 0 14px}}
ul{{list-style:none;padding:0;margin:0}}
li{{padding:12px 0;border-top:1px solid #eef2f4}}
a{{color:#003F62;text-decoration:none;font-weight:600}} a:hover{{text-decoration:underline}}
.m{{font-size:13px;color:#44555d;margin-top:3px}} .why{{font-size:12px;color:#7a868d;margin-top:3px;font-style:italic}}
footer{{margin-top:30px;padding-top:16px;border-top:1px solid #e2e8ec;font-size:12px;color:#8a969d}}
</style>
<h1>Client-alert drafts</h1>
<p class=sub>Generated by the TMT Radar pipeline from the tracker feed · window since {html.escape(fmt(since))} · {len(results)} client(s) with matches. DRAFTS for partner review — verify against the official text before sending.</p>
{''.join(cards)}
<footer>Deterministic match on watch-list regulators + keywords. Replace pipeline/clients.json with the firm roster. Nothing here has been sent.</footer>"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--since", default=(date.today() - timedelta(days=30)).isoformat(),
                    help="only items on/after this date (default: last 30 days)")
    ap.add_argument("--api", action="store_true", help="pull the live connector API instead of data/items.json")
    a = ap.parse_args()

    feed = load_feed(a.since, a.api)
    clients = json.loads((Path(__file__).resolve().parent / "clients.json").read_text())["clients"]

    OUT.mkdir(exist_ok=True)
    results = []
    for c in clients:
        matched = []
        for it in feed:
            reasons = match(it, c["watch"])
            if reasons:
                matched.append((it, reasons))
        matched.sort(key=lambda x: x[0].get("date") or "", reverse=True)
        if matched:
            (OUT / f"{c['id']}.md").write_text(draft_markdown(c, matched, a.since))
            results.append((c, matched))

    (OUT / "index.html").write_text(preview_html(results, a.since))
    total = sum(len(m) for _, m in results)
    print(f"feed: {len(feed)} items since {a.since} | {len(results)} client(s) with matches | "
          f"{total} client-item alerts | drafts -> {OUT}/")
    for c, m in results:
        print(f"  {c['name']:24} {len(m):3} item(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
